# Generated by Django 4.1.4 on 2022-12-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_games_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ac', models.CharField(max_length=5)),
                ('ballpark', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='basic_info',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='stats.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='stats.team'),
        ),
    ]
