# Generated by Django 4.1.4 on 2022-12-14 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_team_game_basic_info_game_date_game_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='stats.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='stats.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ac',
            field=models.CharField(default='', max_length=5),
        ),
    ]
