# Generated by Django 4.1.4 on 2022-12-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_team_short_name_team_team_id_alter_game_away_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='away_sp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='dayNight',
            field=models.CharField(default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_sp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='innings',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='game',
            name='series_type',
            field=models.TextField(default='Regular Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.TextField(default=''),
        ),
    ]
