# Generated by Django 4.1.4 on 2023-01-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_game_attendance_game_away_sp_game_daynight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='basic_info',
            new_name='more_info',
        ),
    ]
