# Generated by Django 4.1.4 on 2023-07-29 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0006_rename_basic_info_game_more_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.TextField(default='undef')),
            ],
        ),
        migrations.CreateModel(
            name='Teams_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('n_games', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('runs_home_avg', models.FloatField()),
                ('runs_away_avg', models.FloatField()),
                ('attendance_max', models.IntegerField()),
                ('attendance_min', models.IntegerField()),
                ('attendance_avg', models.IntegerField()),
                ('duration_min', models.IntegerField()),
                ('duration_max', models.IntegerField()),
                ('duration_avg', models.IntegerField()),
                ('sp_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_rank', to='stats.default_rank')),
                ('teams_losses_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_losses_rank', to='stats.teams_rank')),
                ('teams_wins_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_wins_rank', to='stats.teams_rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_rank', to='stats.default_rank')),
                ('watched_teams_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_rank', to='stats.teams_rank')),
            ],
        ),
    ]
