# Generated by Django 4.1.4 on 2023-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_default_rank_teams_rank_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams_rank',
            name='team',
        ),
        migrations.AlterField(
            model_name='stats',
            name='sp_rank',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='teams_losses_rank',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='teams_wins_rank',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='venue_rank',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='watched_teams_rank',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Default_rank',
        ),
        migrations.DeleteModel(
            name='Teams_rank',
        ),
    ]
