from django.shortcuts import render

info = [{"game_id": 706952, "home_team": "Astros", "home_score": 2, "away_team": "Nationals", "away_score": 0, "time": "17:05", "inning": "End 3", "status": "In Progress"}, {"game_id": 706861, "home_team": "Pirates", "home_score": 1, "away_team": "Red Sox", "away_score": 0, "time": "17:05", "inning": "Middle 4", "status": "In Progress"}, {"game_id": 706815, "home_team": "Rays", "home_score": 2, "away_team": "Twins", "away_score": 2, "time": "17:05", "inning": "Top 4", "status": "In Progress"}, {"game_id": 707065, "home_team": "Yankees", "home_score": 3, "away_team": "Phillies", "away_score": 2, "time": "17:05", "inning": "Middle 3", "status": "In Progress"}, {"game_id": 707005, "home_team": "Cubs", "home_score": 0, "away_team": "D-backs", "away_score": 0, "time": "20:05", "inning": "Top 1", "status": "Pre-Game"}, {"game_id": 706840, "home_team": "Giants", "home_score": 0, "away_team": "Padres", "away_score": 0, "time": "20:05", "inning": "Top 1", "status": "Pre-Game"}, {"game_id": 706809, "home_team": "Rangers", "home_score": 0, "away_team": "Reds", "away_score": 0, "time": "20:05", "inning": "Top 1", "status": "Pre-Game"}, {"game_id": 706983, "home_team": "Guardians", "home_score": 0, "away_team": "Brewers", "away_score": 0, "time": "20:05", "inning": "Top 1", "status": "Pre-Game"}, {"game_id": 706973, "home_team": "Rockies", "home_score": 0, "away_team": "Angels", "away_score": 0, "time": "20:10", "inning": "Top 1", "status": "Pre-Game"}, {"game_id": 706833, "home_team": "Mariners", "home_score": 0, "away_team": "Royals", "away_score": 0, "time": "20:10", "inning": "Top 1", "status": "Pre-Game"}, {"game_id": 706918, "home_team": "Marlins", "home_score": "0", "away_team": "Mets", "away_score": "0", "time": "22:40", "inning": " ", "status": "Pre-Game"}, {"game_id": 706929, "home_team": "Dodgers", "home_score": "0", "away_team": "Athletics", "away_score": "0", "time": "01:05", "inning": " ", "status": "Scheduled"}]

def home(request):
    return render(request,'stats/index.html', {'title': 'Home', 'games': info})

def stats(request):
    return render(request,'stats/index.html')
